const data = [
  {
    requestId: "LAGIN001",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "validate",
  },
  {
    requestId: "LAGIN002",
    partner: "Customer",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "cancelled",
  },
  {
    requestId: "LAGIN003",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "validate",
  },
  {
    requestId: "LAGIN004",
    partner: "Customer",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "draft",
  },
  {
    requestId: "LAGIN005",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "validate",
  },
  {
    requestId: "LAGIN006",
    partner: "Customer",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "draft",
  },
  {
    requestId: "LAGIN007",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "cancelled",
  },
  {
    requestId: "LAGIN008",
    partner: "customer",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "draft",
  },
  {
    requestId: "LAGIN009",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "cancelled",
  },
  {
    requestId: "LAGIN010",
    partner: "Supplier",
    sourceLocation: "Source Location",
    destinationLocation: "Destination Location",
    dateCreated: "4 Apr 2024 - 4:48PM",
    status: "cancelled",
  },
];

export { data };
